version: '3'
services:
   postGIS:
      image: kartoza/postgis:9.6-2.4
      ports:
         - "5432:5432"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
   dblayer:
      build:
         context: dbLayer
      ports:
         - "81:80"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./dbLayer/app:/app
         - ./crimeCSV:/crimeCSV
   precog:
      build:
         context: precog
      ports:
         - "82:80"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./precog/app:/app
   NN_precog:
      build:
         context: NN_precog
      ports:
         - "87:80"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./NN_precog/app:/app
   rec_eng:
      build:
         context: rec_eng
      ports:
         - "86:80"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./rec_eng/app:/app
   stat_precog:
      build:
         context: stat_precog
      ports:
         - "84:80"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./stat_precog/app:/app
   tileserver:
      build:
         context: tileserver-gl
      ports:
         - "85:80"
      restart: always
      volumes:
         - ./data:/data
      networks:
         - db_nw
   mapbox:
      build:
         context: mapbox
      ports:
         - "80:80"
      restart: always
      networks:
         - db_nw
      volumes:
         - ./mapbox/app:/app
   jupyter:
      image: jupyter/datascience-notebook
      ports:
         - "8888:8888"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
networks:
   db_nw:
      driver: bridge
