version: '3'
services:
   postGIS:
      image: mdillon/postgis
      ports:
         - "5432:5432"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
networks:
   db_nw:
      driver: bridge
