version: '3'
services:
   postGIS:
      image: kartoza/postgis
      ports:
         - "5432:5432"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
   dbLayer:
      build:
         context: dbLayer
      image: nginx
      ports:
         - "81:80"
      networks:
         - db_nw
      env_file:
         - env_file
networks:
   db_nw:
      driver: bridge
