version: '3'
services:
   postGIS:
      image: kartoza/postgis:9.6-2.4
      ports:
         - "5432:5432"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./postgres-data:/var/lib/postgresql/data/pgdata
   dblayer:
      build:
         context: dbLayer
      ports:
         - "81:80"
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./crimeCSV:/crimeCSV
   precog:
      build:
         context: precog
      ports:
         - "82:80"
      networks:
         - db_nw
      env_file:
         - env_file
   stat_precog:
      build:
         context: stat_precog
      ports:
         - "84:80"
      networks:
         - db_nw
      env_file:
         - env_file
   basicgui:
      build:
         context: webGUI
      ports:
         - "83:80"
      networks:
         - db_nw
      env_file:
         - env_file
networks:
   db_nw:
      driver: bridge
