version: '3'
services:
   postGIS:
      image: kartoza/postgis:9.6-2.4
      ports:
         - "5432:5432"
      restart: always
      networks:
         - db_nw
      env_file:
         - env_file
   dblayer:
      build:
         context: dbLayer
      ports:
         - "81:80"
      networks:
         - db_nw
      env_file:
         - env_file
      volumes:
         - ./crimeCSV:/crimeCSV
   precog:
      build:
         context: precog
      ports:
         - "82:80"
      networks:
         - db_nw
      env_file:
         - env_file
   stat_precog:
      build:
         context: stat_precog
      ports:
         - "84:80"
      networks:
         - db_nw
      env_file:
         - env_file
   tileserver:
      build:
         context: tileserver-gl
      ports:
         - "85:80"
      volumes:
         - ./data:/data
      networks:
         - db_nw
   mapbox:
      build:
         context: mapbox
      ports:
         - "80:80"
      networks:
         - db_nw
networks:
   db_nw:
      driver: bridge
